# permissions for end users to view caistios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: caistio-viewer-role
rules:
- apiGroups:
  - operator.ca.com
  resources:
  - caistios
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.ca.com
  resources:
  - caistios/status
  verbs:
  - get
