# permissions for end users to edit caistios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: caistio-editor-role
rules:
- apiGroups:
  - operator.ca.com
  resources:
  - caistios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.ca.com
  resources:
  - caistios/status
  verbs:
  - get
